/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boot.security.browser;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class BrowserApplication {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new BrowserApplication().getGreeting());
    }
}
