/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boot.security.browser;

import boot.security.core.CoreApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Import;

@SpringBootApplication
@Import(CoreApplication.class)
// @EnableJdbcHttpSession
public class BrowserApplication {
  public static void main(String[] args) {
    System.out.println(new BrowserApplication().getGreeting());
  }

  public String getGreeting() {
    return "Hello world.";
  }
}
