/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boot.security.app;

public class AppApplication {
  public static void main(String[] args) {
    System.out.println(new AppApplication().getGreeting());
  }

  public String getGreeting() {
    return "Hello world.";
  }
}
