/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boot.security.core;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CoreApplication {
  public boolean someLibraryMethod() {
    return true;
  }
}
