/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boot.security.core;

public class CoreApplication {
    public boolean someLibraryMethod() {
        return true;
    }
}
